import fs from 'node:fs';
import path from 'node:path';
import { NGINX_DEFAULTS } from './constants.mjs';
import { certPaths, nginxStagingFile } from './paths.mjs';
import { buildAdaptiveMapBlocks, nginxMapVariable } from './web.mjs';
import {
  filterApiSurfacesForSurface,
  resolveDomainSurfaceId,
  resolveUpstreams,
  upstreamForSurface,
} from './api.mjs';
import { loadProfileEnv } from './topology-env.mjs';

function requireUpstream(upstreams, surfaceId) {
  const upstream = upstreamForSurface(upstreams, surfaceId);
  if (!upstream) {
    throw new Error(`missing upstream for surface "${surfaceId}"`);
  }
  return upstream;
}

function renderProxyLocation(prefix, upstream, options = {}) {
  const ws = options.websocket
    ? `
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";`
    : '';
  const locationPrefix = prefix.endsWith('/') ? prefix : `${prefix}/`;
  const apiPathStyle = options.apiPathStyle ?? 'full-prefix';
  let proxyTarget = upstream;
  if (apiPathStyle === 'strip-prefix') {
    proxyTarget = upstream.endsWith('/') ? upstream : `${upstream}/`;
  }
  return `    location ${locationPrefix} {
        proxy_pass ${proxyTarget};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;${ws}
        proxy_buffering off;
        proxy_read_timeout ${NGINX_DEFAULTS.proxyReadTimeout};
        proxy_send_timeout ${NGINX_DEFAULTS.proxySendTimeout};
    }`;
}

function renderHealthLocations(upstream) {
  return `    location = /healthz {
        proxy_pass ${upstream}/healthz;
        proxy_set_header Host $host;
    }

    location = /readyz {
        proxy_pass ${upstream}/readyz;
        proxy_set_header Host $host;
    }`;
}

function renderWebSnippets(exposeItem) {
  const snippets = [];
  for (const root of exposeItem.webRoots ?? []) {
    const snippetName = `${exposeItem.domain}.web.${root.surface}.conf`;
    const content = `root ${root.path};\ntry_files $uri $uri/ /index.html;\n`;
    snippets.push({ snippetName, content, surface: root.surface });
  }
  return snippets;
}

export function renderNginxSite(plan, domain, options = {}) {
  const exposeItem = plan.expose.find((item) => item.domain === domain);
  if (!exposeItem) {
    throw new Error(`domain "${domain}" not found in deploy plan`);
  }

  const profileEnv =
    plan.profileEnv ?? loadProfileEnv(plan.repoRoot ?? '', plan.topology, plan.profileId);
  const upstreams =
    plan.upstreams ?? resolveUpstreams(plan.topology, plan.overrides, profileEnv);
  const surfaceId = resolveDomainSurfaceId(plan.topology, domain);
  const domainUpstream = requireUpstream(upstreams, surfaceId);
  const domainApiSurfaces = filterApiSurfacesForSurface(plan.apiSurfaces, surfaceId);
  const certName =
    exposeItem.tls === 'off' || exposeItem.tls === 'managed' ? 'sdkwork.com' : exposeItem.tls;
  const certs = certPaths(certName, plan.overrides);
  const mapBase = nginxMapVariable(plan.appId);
  // Snippet paths are dialect references for rendered sidecars / webserver
  // import overlays. Stock /etc/nginx is not the live edge (NGINX_SPEC.md §0).
  const snippetDir = options.snippetDir ?? 'deployments/webserver/snippets';
  const serverNames = [exposeItem.domain, ...(exposeItem.aliases ?? [])].join(' ');

  const baseDomainOf = (host) => String(host).split('.').slice(-2).join('.');
  const primaryBase = baseDomainOf(exposeItem.domain);
  const crossBaseDomains = (exposeItem.aliases ?? [])
    .filter((alias) => baseDomainOf(alias) !== primaryBase);
  if (crossBaseDomains.length > 0) {
    console.warn(
      `[nginx-render] ${exposeItem.domain}: aliases ${crossBaseDomains.join(', ')} span`
      + ` additional base domains; the certificate must cover every bound host`
      + ` (SAN or one wildcard/SAN per base domain, NGINX_SPEC.md section 3)`,
    );
  }

  const header = [
    '# GENERATED BY sdkwork-deploy',
    `# domain: ${exposeItem.domain}`,
    `# appId: ${plan.appId}`,
    `# profile: ${plan.profileId}`,
    `# layout: ${plan.installLayout}`,
    `# deploy: ${exposeItem.siteFile}`,
    `# surface: ${surfaceId}`,
    `# upstream: ${domainUpstream}`,
    '',
  ];

  const mapBlocks = [];
  const webMode = exposeItem.web?.mode;
  const useAdaptive =
    (exposeItem.mode === 'web' || exposeItem.mode === 'web+api') &&
    webMode === 'adaptive' &&
    (exposeItem.webRoots?.length ?? 0) >= 2;

  if (useAdaptive) {
    mapBlocks.push(...buildAdaptiveMapBlocks(plan.appId, plan.overrides));
  }

  const serverLocations = [];

  if (exposeItem.mode === 'api' || exposeItem.mode === 'web+api') {
    const apiPathStyle = exposeItem.apiPathStyle ?? 'full-prefix';
    for (const api of domainApiSurfaces) {
      serverLocations.push(
        renderProxyLocation(api.prefix, domainUpstream, { apiPathStyle }),
      );
    }
    if (plan.websocketPath && surfaceId === 'application.public-ingress') {
      serverLocations.push(
        renderProxyLocation(plan.websocketPath, domainUpstream, { websocket: true }),
      );
    }
    serverLocations.push(renderHealthLocations(domainUpstream));
  }

  if ((exposeItem.mode === 'web' || exposeItem.mode === 'web+api') && webMode) {
    if (useAdaptive) {
      const mapVar = `$${mapBase}_surface_final`;
      serverLocations.push(`    location / {
        try_files /__sdkwork_adaptive_dispatch__ ${mapVar};
        add_header Vary "User-Agent, Sec-CH-UA-Mobile" always;
    }

    location @pc {
        root ${exposeItem.webRoots.find((root) => root.surface === 'pc')?.path ?? `${snippetDir}/../web/pc`};
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location @h5 {
        root ${exposeItem.webRoots.find((root) => root.surface === 'h5')?.path ?? `${snippetDir}/../web/h5`};
        index index.html;
        try_files $uri $uri/ /index.html;
    }`);
    } else if (webMode === 'static-fallback') {
      const root =
        exposeItem.web?.staticRoot
        ?? exposeItem.webRoots?.[0]?.path
        ?? '/var/www/html';
      serverLocations.push(`    location / {
        root ${root};
        index index.html;
        try_files $uri $uri/ =404;
    }`);
    } else {
      const root = exposeItem.webRoots?.[0]?.path ?? '/var/www/html';
      serverLocations.push(`    location / {
        root ${root};
        try_files $uri $uri/ /index.html;
    }`);
    }
  }

  for (const snippet of plan.overrides?.nginx?.snippets ?? []) {
    serverLocations.push(`    include ${snippet};`);
  }

  const locationBlock = serverLocations.join('\n\n');
  const clientMaxBodySize =
    plan.overrides?.nginx?.clientMaxBodySize ?? NGINX_DEFAULTS.clientMaxBodySize;

  let servers = '';
  if (exposeItem.tls !== 'off') {
    servers = `server {
    listen 80;
    server_name ${serverNames};
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name ${serverNames};

    ssl_certificate     ${certs.fullchain};
    ssl_certificate_key ${certs.privkey};
    ssl_protocols TLSv1.2 TLSv1.3;

    client_max_body_size ${clientMaxBodySize};

${locationBlock}
}`;
  } else {
    servers = `server {
    listen 80;
    server_name ${serverNames};

    client_max_body_size ${clientMaxBodySize};

${locationBlock}
}`;
  }

  const mainConfig = [...header, ...mapBlocks, servers].filter(Boolean).join('\n\n') + '\n';
  const snippets = renderWebSnippets(exposeItem);

  return { mainConfig, snippets, stagingFile: nginxStagingFile(domain), snippetDir };
}

export function writeNginxRender(repoRoot, plan, domain, options = {}) {
  const { mainConfig, snippets, stagingFile, snippetDir: defaultSnippetDir } = renderNginxSite(
    plan,
    domain,
    options,
  );
  const stagingPath = path.join(repoRoot, stagingFile);
  const mainPath = options.outputRoot
    ? path.join(path.resolve(repoRoot, options.outputRoot), path.basename(stagingFile))
    : stagingPath;

  fs.mkdirSync(path.dirname(mainPath), { recursive: true });
  fs.writeFileSync(mainPath, mainConfig, 'utf8');

  const snippetDir = options.snippetDir
    ? path.resolve(repoRoot, options.snippetDir)
    : path.join(path.dirname(mainPath), 'snippets', 'sdkwork');
  fs.mkdirSync(snippetDir, { recursive: true });

  const snippetOutputs = [];
  for (const snippet of snippets) {
    const snippetPath = path.join(snippetDir, snippet.snippetName);
    fs.writeFileSync(snippetPath, snippet.content, 'utf8');
    snippetOutputs.push(snippetPath);
  }

  return { mainPath, snippetOutputs, snippetDir: snippetDir || defaultSnippetDir };
}
