environment = "production"

[http]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["router.sdkwork.com", "cloudrouter.sdkwork.com", "router-admin.sdkwork.com", "router-open.sdkwork.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "sdkwork.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["router.birdcoder.com", "router-admin.birdcoder.com", "router-open.birdcoder.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "birdcoder.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["router.dtupay.com", "router-admin.dtupay.com", "router-open.dtupay.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "dtupay.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["router.sdkwork.cn", "router-admin.sdkwork.cn", "router-open.sdkwork.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "sdkwork.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["router.birdcoder.cn", "router-admin.birdcoder.cn", "router-open.birdcoder.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "birdcoder.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["router.dtupay.cn", "router-admin.dtupay.cn", "router-open.dtupay.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "dtupay.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["router.skubc.com", "router-admin.skubc.com", "router-open.skubc.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "skubc.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["router.skubc.cn", "router-admin.skubc.cn", "router-open.skubc.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "skubc.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["router.zowalk.com", "router-admin.zowalk.com", "router-open.zowalk.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "zowalk.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["router.zowalk.cn", "router-admin.zowalk.cn", "router-open.zowalk.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "zowalk.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["router.offer86.com", "router-admin.offer86.com", "router-open.offer86.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "offer86.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["router.offer86.cn", "router-admin.offer86.cn", "router-open.offer86.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "offer86.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["router.86offer.com", "router-admin.86offer.com", "router-open.86offer.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "86offer.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["router.86offer.cn", "router-admin.86offer.cn", "router-open.86offer.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "86offer.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

